### ISSUE TITLE
中文显示

### ISSUE THREAD

**Issue by xfmujie** [SuInk/resin-esp32c3#1]
你好作者，请问有考虑加入中文显示吗？我用网上的一些方法通过引入TFT_espi的库，编译失败，说是Adafruit_ST7735 tft =……这一行声明冲突，请问怎么解决？谢谢

**Comment by SuInk** [comment]
你只使用TFT_espi应该就能驱动屏幕，可以把下面这两个库去掉
``` c
#include <Adafruit_GFX.h>
#include <Adafruit_ST7735.h> 
```
具体我也没用过TFT_espi这个库
